# Site settings
title: 张小豪
description: "个人工作记录"
url: "http://zhangzhiyuan0820.github.io/blog"
author:
  name: "Jacopo Rabolini"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl:  /zhangzhiyuan0820.github.io/blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
